### PR TITLE
Fixes in 3den placed village

### PR DESCRIPTION
**Pull request by jmlane**
Cherrypicked 72f80dc from [orbat-properties-remoteexec](https://github.com/AthenaSecurityGroup/Sandbox.Altis/tree/orbat-properties-remoteexec) since it seemed to be a general update to the scenario, not something specific to that branch.

### CODE REVIEW

**Comment by jmlane** [comment]
@DEL-J Can you provide a brief description of the changes?

**Comment by DEL-J** [comment]
1. Moved a store from the middle of a road to where it should go.
2. Replaced a gyro kiosk with a proper gas station building.
3. Cleaned up the placement of some hand rails.

Where do I stick this?

**Comment by jmlane** [comment]
Normally in the description part of the commit message. Ultimately the merge commit messages on PR completion is where it matters, but it makes the review/merging process easier if all the commits have enough information for someone to skim the change and know what was affected.

**Comment by DEL-J** [comment]
How do I access that description area from here?

**Comment by jmlane** [comment]
The commit message can't be changed without changing the branch history. The merge commit message can be provided when the PR is ready to be merged and resolved.

I need you or @Diffusion9 to approve the changes because I opened the PR. At that point, the merge option will be available.

**Review by DEL-J — APPROVED** [review]
Approving here, hope that's what I'm supposed to do.

**Pull request merged**
